apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-alertmanager
  namespace: monitoring
  labels:
    app: prometheus
    component: alertmanager
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: prometheus-ebs
  resources:
    requests:
      storage: 5Gi
