apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pod4-app
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: pod4
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s

