apiVersion: v1
kind: ServiceAccount
metadata:
  name: bank46-secret-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::245000192780:role/Bank46-SecretAccess-Role
  labels:
    app: bank46
    component: secret-access
