project              = "pod4bankapp"
environment          = "bootstrap"
aws_region           = "us-east-1"
bucket_name          = "pod4bankapp-tfstate-bucket"
dynamodb_table_name  = "pod4bankapp-tf-locks"
